# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ChannelResignTool' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for ChannelResignTool

pod 'MJExtension'

end

# 解决警告
# /Users/zclongjie/Desktop/tools/ChannelResignTool/ChannelResignTool/Pods/Pods.xcodeproj warning project: The macOS deployment target 'MACOSX_DEPLOYMENT_TARGET' is set to 10.8, but the range of supported deployment target versions is 10.9 to 12.3.99.
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.build_settings['MACOSX_DEPLOYMENT_TARGET'].to_f < 10.9
        config.build_settings['MACOSX_DEPLOYMENT_TARGET'] = '10.9'
      end
    end
  end
end
